lxml: forcely remove ${S}/.pc
${S}/.pc was created and it caused building error such as:

ERROR: python3-lxml-native-3.4.0-r0 do_debian_patch:
please re-consider DEBIAN_PATCH_TYPE

We no longer need ${S}/.pc, so remove it.

Signed-off-by: Daichi Fukui <daichi1.fukui@toshiba.co.jp>