readline: Fix missing symbols
libreadline fails to link against libtermcap and cause various missing symbols issues.
Fix error when build bluez5:
  | .../recipe-sysroot/usr/lib/libreadline.so: undefined reference to 'tputs'
  | .../recipe-sysroot/usr/lib/libreadline.so: undefined reference to 'tgoto'
  | .../recipe-sysroot/usr/lib/libreadline.so: undefined reference to 'tgetflag'
  | ...

Signed-off-by: Trung Do <trung.dothanh@toshiba-tsdv.com>