qtbase-opensource-src: Fix problem with compiler feature in simd.prf
Commit 3b00cc4 from Qt use 'gcc' feature in simd.prf.
This makes cross-compiler cannot be detected,
then HEADERS and SOURCES for ssse3 won't be defined.
Apply patch for reverting this commit.
Fix error:
  | .../src/gui/image/qimage_conversions.cpp:2165: undefined reference to 'convert_RGB888_to_RGB32_ssse3(...)'
  | .obj/qdrawhelper.o: In function 'qInitDrawhelperAsm()':
  | .../src/gui/painting/qdrawhelper.cpp:6659: undefined reference to 'qt_blend_argb32_on_argb32_ssse3(...)'
  | collect2: error: ld returned 1 exit status
  | Makefile:778: recipe for target '../../lib/libQt5Gui.so.5.3.2' failed

Add ${EXTRA_OECONF} into do_configure to other layers can add options through this variable.

We don't provide ${PN}, remove it out of RDEPENDS of ${PN}-dev.

Signed-off-by: Trung Do <trung.dothanh@toshiba-tsdv.com>