libxml: Fix libxml2-utils packaging issue
libxml2 package contains xmlcatalog and xmllint commands, which should
be provided by libxml2-utils package.

So, empty libxml2-utils package causes following error when add
libxml2-utils to rootfs.

ERROR: core-image-minimal-1.0-r0 do_rootfs: Unable to install packages.
Command
'/home/masami/metadebian/build/tmp/work/qemuarm64-deby-linux/core-image-minimal/1.0-r0/recipe-sysroot-native/usr/bin/apt-get
install --force-yes --allow-unauthenticated libxml2-utils
packagegroup-core-boot run-postinsts' returned 100:
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package libxml2-utils

Use PACKAGE_BEFORE_PN to create libxml2-utils package before create
libxml2 as poky does.