tcl: Fix build for expect
Fix the following error:
```
ERROR: expect-5.45.4-r0 do_package_qa: QA Issue: expect: The compile log
indicates that host include and/or library paths were used.
```

Signed-off-by: Nobuhiro Iwamatsu <nobuhiro1.iwamatsu@toshiba.co.jp>