classes: debian-source: Fix key error when adding new package
When adding a new package, old_pkg_dev_map doesn't have the package in it.
Therefore, it needs to check "package" is in the old_pkg_dpv_map or not.

This commit fixes follogin error.

    >        if debian.debian_support.version_compare(old_pkg_dpv_map[package], noepoch_dpv) > 0:
                 continue
KeyError: 'apparmor'

ERROR: Command execution failed: Traceback (most recent call last):
  File "/home/masami/metadebian/poky/bitbake/lib/bb/command.py", line 103, in runAsyncCommand
    self.cooker.updateCache()
  File "/home/masami/metadebian/poky/bitbake/lib/bb/cooker.py", line 1562, in updateCache
    self.parser = CookerParser(self, filelist, masked)
  File "/home/masami/metadebian/poky/bitbake/lib/bb/cooker.py", line 2005, in __init__
    self.start()
  File "/home/masami/metadebian/poky/bitbake/lib/bb/cooker.py", line 2012, in start
    bb.event.fire(bb.event.ParseStarted(self.toparse), self.cfgdata)
  File "/home/masami/metadebian/poky/bitbake/lib/bb/event.py", line 215, in fire
    fire_class_handlers(event, d)
  File "/home/masami/metadebian/poky/bitbake/lib/bb/event.py", line 124, in fire_class_handlers
    execute_handler(name, handler, event, d)
  File "/home/masami/metadebian/poky/bitbake/lib/bb/event.py", line 96, in execute_handler
    ret = handler(event)
  File "/home/masami/metadebian/poky/meta-debian/classes/debian-source.bbclass", line 273, in debian_source_eventhandler
    parse_Sources_xz(old_pkg_dpv_map, update_target['debian_security_update_enabled'], d)
  File "/home/masami/metadebian/poky/meta-debian/classes/debian-source.bbclass", line 195, in parse_Sources_xz
    repack_version, directory, files, md5sum, sha256sum, debian_security_update_enabled, d)
  File "/home/masami/metadebian/poky/meta-debian/classes/debian-source.bbclass", line 116, in save_to_file
    if debian.debian_support.version_compare(old_pkg_dpv_map[package], noepoch_dpv) > 0:
KeyError: 'apparmor'

Signed-off-by: Masami Ichikawa <masami.ichikawa@miraclelinux.com>