libbsd: Fix libbsd build error
When build libbsd, got following error.

ERROR: libbsd-0.9.1-r0 do_debian_patch: DEBIAN_QUILT_PATCHES is null,
but
/home/masami/metadebian/build/tmp/work/aarch64-deby-linux/libbsd/0.9.1-r0/libbsd-0.9.1/debian/patches/series
exists
ERROR: libbsd-0.9.1-r0 do_debian_patch: Please consider to redefine
DEBIAN_QUILT_PATCHES
ERROR: libbsd-0.9.1-r0 do_debian_patch: Function failed: do_debian_patch
(log file is located at
/home/masami/metadebian/build/tmp/work/aarch64-deby-linux/libbsd/0.9.1-r0/temp/log.do_debian_patch.1062)
ERROR: Logfile of failure stored in:
/home/masami/metadebian/build/tmp/work/aarch64-deby-linux/libbsd/0.9.1-r0/temp/log.do_debian_patch.1062
ERROR: Task
(/home/masami/metadebian/poky/meta-debian/recipes-debian/libbsd/libbsd_debian.bb:do_debian_patch)
failed with exit code '1'

The libbsd debian package contains patch file now so it needs to remove
'DEBIAN_QUILT_PATCHES = ""' line.

Signed-off-by: Masami Ichikawa <masami.ichikawa@miraclelinux.com>