mysql-native: Use system zlib instead of bundled zlib
Fix error:
  | zlib/zlib.h:1420:9: error: unknown type name ‘z_size_t’
  | ZEXTERN z_size_t ZEXPORT gzfread OF((voidp buf, z_size_t size, z_size_t nitems,
  |         ^

Also remove useless DEPENDS.

Signed-off-by: Trung Do <trung.dothanh@toshiba-tsdv.com>
Signed-off-by: Kazuhiro Hayashi <kazuhiro3.hayashi@toshiba.co.jp>