grub2: Fix build error with freetype
Building failed when built target 64bit on system 32bit and freetype existed in sysroots.
Cross script freetype-config makes 'build_freetype_cflags' and 'build_freetype_libs'
point to target sysroots which should be native sysroots,
because these variables are used with 'BUILD_CC' to build native binary file.
Fix error:
  | .../include/freetype2/config/ftconfig.h:41:42: fatal error: freetype2/config/ftconfig-32.h: No such file or directory
  |  #include <freetype2/config/ftconfig-32.h>
  |                                           ^
  | compilation terminated.

Signed-off-by: Trung Do <trung.dothanh@toshiba-tsdv.com>