at: Fix parallel build
The old patch make \"\$(YACC) -d parsetime.y\" run twice and it can cause
error in parallel build.
Improve this patch to prevent this problem.

With old patch, some errors can happened like:
  | y.tab.c:1368:5: error: label 'yyerrlab' used but not defined
  |      goto yyerrlab;

or
  | y.tab.c:656:7: error: expected identifier or '(' before 'if'
  |        16,    17,    18,    93,    82,    83,    48,    49,    50,    51,
  |        ^
  | y.tab.c:660:19: error: expected declaration specifiers or '...' before string constant
  |
  |                    ^
  | y.tab.c:661:19: error: unknown type name 'yystos'
  |  static const yytype_int8 yycheck[] =

Signed-off-by: Trung Do <trung.dothanh@toshiba-tsdv.com>
Signed-off-by: Kazuhiro Hayashi <kazuhiro3.hayashi@toshiba.co.jp>