rdesktop: Fix error when build for qemuppc
We are cross compiling, set 'fu_cv_sys_stat_statvfs64=cross'
to prevent sys_stat_statvfs64 is 'yes' by running test code in configure,
because it make error when build for qemuppc target:
  | disk.c:726:18: error: storage size of 'stat_fs' isn't known
  |   struct STATFS_T stat_fs;

Signed-off-by: Trung Do <trung.dothanh@toshiba-tsdv.com>